name: Pulumi AWS Manual Deployment

on:
  workflow_dispatch:
    inputs:
      command:
        description: 'Choose an command to perform'
        required: true
        default: 'preview'
        type: choice
        options:
          - up
          - preview
          - delete 
      stackName:
        description: 'Choose an existing stack name'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev

jobs:
  perform:
    name: Action ${{ inputs.command }}
    runs-on: ubuntu-latest
    env:
      PULUMI_CONFIG_PASSPHRASE: ""
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE }}
          role-session-name: PulumiSession
      - run: pip install -r requirements.txt
      - name: Login to Pulumi (local)
        run: | 
          pulumi login "${{ secrets.AWS_S3_BACKEND }}/${{ inputs.stackName }}"
      - name: Stack Config
        run: | 
          pulumi stack init ${{ inputs.stackName }}
          pulumi config set aws:region ${{ secrets.AWS_REGION }}
      - name: Perform preview command
        if: ${{ inputs.command == 'preview' }}
        run: pulumi preview

      - name: Perform run command
        if: ${{ inputs.command == 'up' }}
        run: pulumi up -y

      - name: Perform delete command
        if: ${{ inputs.command == 'delete' }}
        run: pulumi delete -y
